### ISSUE TITLE
Unable to get AnimationData

### ISSUE THREAD

**Issue by honda6** [richard-roberts/PhD#2]
hi, the folder tests/AnimationData is unavailable now, can you upload a new one?

**Comment by richard-roberts** [comment]
Hi there.

I haven't maintained this repository properly, sorry! I also don't have the folder anymore.

If won't be possible to run the test cases that I used to have at this point (I've removed two of the implementations, and instead just kept the latest Maya version). 

If you just wanted the animation data itself, you can find the experiment data here: https://github.com/richard-roberts/SalientPoses/tree/master/data. Each subfolder has the original animation data, which I downloaded from [Mixamo](https://www.mixamo.com) and imported into Maya. There's also a custom CSV file. Unfortunately, the original FBX files from Mixamo are missing :(

Does that help? I might be able to recover some of the original set up if you really need it, let me know.

**Comment by honda6** [comment]
Yep, i found the original animation data by the link you provided, but maybe the csv files in 'test/AnimationData/analysis' and in 'test/AnimationData/selection' are missing. Can you provide these two kinds of csv data, or can you tell me how to generate them?

**Comment by richard-roberts** [comment]
The algorithm basically works in three steps:

1 - measure the error of all keyframe pairs (saving these into an "error table"). 
2 - build all optimal sets of keyframes 
3 - given a specific set of keyframes, interpolate the keyframes using splines

I just used those folders to save intermediary outputs from steps 1 and 2. 

For `test/AnimationData/analysis`, the [error table save function](https://github.com/richard-roberts/SalientPosesMaya/blob/master/src/ErrorTable.cpp#L54) creates a CSV file, which I would save to that folder. To recreate the folder, do this once for each of the animation data files. 

For `test/AnimationData/selection`, the [SelectionProxy save function](https://github.com/richard-roberts/SalientPosesMaya/blob/master/src/SelectionProxy.cpp#L24) creates a CV file, which I would save to that folder. To recreate the folder, do the same as above.

Not 100% sure, but I'm guessing you could still compile my old CLI version using [this main file](https://github.com/richard-roberts/SalientPosesMaya/blob/master/src/main.cpp). Then if you add statements to save the error table and the selection proxy you could probably recreate the original data for the tests.  IIRC, the tests just ran the algorithm on these examples, saved the results from the steps 1-3 to CSV and used `diff` to check that the result was the same as before (so I'd notice unexpected changes to the results when developing). Hope that helps!

**Comment by honda6** [comment]
get it~ thanks a lot!

**Comment by richard-roberts** [comment]
No problem - sorry this is a mess!

Feel free to reach out anytime if you've got questions or would like some help :)
